name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all -- --test-threads 1